---
azure_resource_group: ""
configmap_secret: ""
controller_state: absent
disable_image_migration: false
disable_image_copy: false
disable_pv_migration: false
excluded_resources:
  - imagetags
  - templateinstances
  - clusterserviceversions
  - packagemanifests
  - subscriptions
  - servicebrokers
  - servicebindings
  - serviceclasses
  - serviceinstances
  - serviceplans
  - operatorgroups
  - events
  - events.events.k8s.io
  - rolebindings.authorization.openshift.io
proxy_secret_name: "migration-proxy"
http_proxy: "{{ lookup( 'env', 'HTTP_PROXY') }}"
https_proxy: "{{ lookup( 'env', 'HTTPS_PROXY') }}"
no_proxy: "{{ lookup( 'env', 'NO_PROXY') }}"
stunnel_tcp_proxy: ""
stunnel_verify_ca: true
stunnel_verify_ca_level: "2"
image_pull_policy: Always
cluster_subdomain: ""
rsync_transfer_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_RSYNC_TRANSFER') }}"
source_rsync_pod_cpu_limits: "1"
source_rsync_pod_memory_limits: "1Gi"
source_rsync_pod_cpu_requests: "100m"
source_rsync_pod_memory_requests: "1Gi"
stunnel_pod_cpu_limits: '1'
stunnel_pod_cpu_requests: '100m'
stunnel_pod_memory_limits: '1Gi'
stunnel_pod_memory_requests: '1Gi'
target_rsync_pod_cpu_limits: '1'
target_rsync_pod_cpu_requests: '100m'
target_rsync_pod_memory_limits: '1Gi'
target_rsync_pod_memory_requests: '1Gi'
enable_dvm_pv_resizing: false
hook_runner_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_HOOK_RUNNER') }}"
internal_cluster_api_url: "https://kubernetes.default.svc.cluster.local"
internal_discovery_svc_url: "http://discovery.{{ mig_namespace }}.svc.cluster.local"
jaeger_enabled: "false"
mig_controller_limits_cpu: "1"
mig_controller_limits_memory: "10Gi"
mig_controller_requests_cpu: "100m"
mig_controller_requests_memory: "350Mi"
mig_controller_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_CONTROLLER') }}"
mig_controller_enable_cache: false
discovery_collect_events: true
discovery_volume_path: "/var/cache/discovery"
mig_operator_version: "latest"
mig_pv_move_storageclasses: []
mig_pv_limit: "100"
mig_pod_limit: "100"
mig_namespace_limit: "10"
mig_namespace: "{{ lookup( 'env', 'WATCH_NAMESPACE') | default('openshift-migration') }}"
mig_ui_cluster_api_endpoint: ""
mig_ui_configmap_data: ""
mig_ui_configmap_name: mig-ui-config
mig_ui_config_namespace: openshift-migration
mig_ui_oauth_user_scope: "user:full"
mig_ui_oauth_redirect_url: ""
mig_ui_oauth_secret: ""
mig_ui_image_fqin: "{{ lookup( 'env', 'RELATED_IMAGE_UI') }}"
log_reader_state: absent
mig_log_reader_image_fqin: "{{ lookup( 'env', 'RELATED_IMAGE_MIG_LOG_READER') }}"
migration_log_reader: true
migration_registry_image_fqin: "{{ lookup( 'env', 'RELATED_IMAGE_MIGRATION_REGISTRY') }}"
migration_stage_image_fqin: "{{ lookup('env', 'RELATED_IMAGE_RSYNC_TRANSFER') }}"
migration_rsync_privileged: false
migration_rsync_super_privileged: false
enable_intelligent_pv_resize: true
registry: "{{ lookup( 'env', 'REGISTRY') }}"
project: "{{ lookup( 'env', 'PROJECT') }}"
restic_pv_host_path: /var/lib/kubelet/pods
restic_requests_cpu: "100m"
restic_timeout: 1h
restic_supplemental_groups: []
ui_state: absent
velero_aws_secret_name: cloud-credentials
velero_gcp_secret_name: cloud-credentials-gcp
velero_azure_secret_name: cloud-credentials-azure
velero_use_legacy_aws: false
mtc_velero_plugin_fqin: "{{ lookup('env', 'RELATED_IMAGE_PLUGIN') }}"
velero_requests_cpu: "100m"
velero_state: absent
